# Generated by Django 3.2.25 on 2025-04-01 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.TextField(db_index=True, default=utils.shortcuts.rand_str, max_length=32, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.TextField()),
                ('similarity_threshold', models.FloatField()),
                ('status', models.TextField(choices=[('待处理', '待处理'), ('处理中', '处理中'), ('完成', '完成'), ('失败', '失败')], db_index=True, default='待处理')),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='contest.contest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='problem.problem')),
                ('submissions', models.ManyToManyField(blank=True, related_name='detection_tasks', to='submission.Submission')),
            ],
            options={
                'db_table': 'detection',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DetectionComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(null=True)),
                ('user_a_id', models.IntegerField(db_index=True, default=0)),
                ('user_a_code', models.TextField(default='')),
                ('user_b_id', models.IntegerField(db_index=True, default=0)),
                ('user_b_code', models.TextField(default='')),
                ('lines_a', models.TextField(default='')),
                ('lines_b', models.TextField(default='')),
                ('similarity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='detection.detection')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_comparisons', to='problem.problem')),
            ],
            options={
                'db_table': 'detection_comparison',
                'ordering': ('-created_at',),
                'unique_together': {('detection', 'user_a_id', 'user_b_id', 'lines_a', 'lines_b')},
            },
        ),
    ]
