# Generated by Django 3.2.25 on 2025-05-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGCDetectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(null=True)),
                ('similarity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aigc_detection_results', to='detection.detection')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aigc_detection_results', to='problem.problem')),
            ],
            options={
                'db_table': 'aigc_detection_result',
                'ordering': ('-created_at',),
            },
        ),
    ]
