# Generated by Django 3.2.25 on 2025-05-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_detection_algorithm_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigcdetectionresult',
            name='user_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aigcdetectionresult',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
